language: cpp

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  # g++ 4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install build-essential

  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; CC="gcc-4.8"; fi

  - make get-deps

script:
  - make

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: true
