language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: false

compiler:
  - gcc
  - clang

branches:
  only:
    - master

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - make get-deps

script:
  - make

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: true
